INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'HONDA','Civic','EJ','1.6 i coupé 125cv','1996','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'HONDA','Civic','ED','1.6 i 130cv','1989','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'HONDA','S2000','AP','2.0 i VTEC 240CV','1999','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'HONDA','NSX','(07/2001 - 12/2005','3.2 V6 24V Coupé 280CV','2002','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'TOYOTA','SUPRA','(JZA80)(05/1993 - 05/1996)','3.0 i Turbo 330cv','1995','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'TOYOTA','SUPRA','(JZA80)(05/1993 - 05/1996)','3.0 i Turbo 330cv Boite Auto','1994','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'TOYOTA','SUPRA','(JZA80)(05/1993 - 05/1996)','3.0 i 230cv Boite Auto','1994','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'TOYOTA','SUPRA','(MA70)(01/1986 - 04/1993)','3.0 24v 204cv Boite Auto','1991','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'TOYOTA','SUPRA','(MA70)(01/1986 - 04/1993)','3.0 24v 204cv','1993','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'TOYOTA','SUPRA','(MA70)(01/1986 - 04/1993)','3.0 Turbo 234cv Boite Auto','1986','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'TOYOTA','SUPRA','(DB)(03/2019 - maintenant)','GR 3.0 Turbo 340cv Boite Auto','2021','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'TOYOTA','SUPRA','(DB)(03/2019 - maintenant)','GR 3.0 Turbo 340cv Boite Auto','2021','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'TOYOTA','MR2','MR2(10/1989 - 11/1989)','2.0 i coupé 120cv','1989','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'TOYOTA','MR2','MR2(10/1989 - 11/1989)','2.0 i coupé 156cv','1992','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'TOYOTA','MR2','MR2(10/1989 - 11/1989)','2.0 i coupé 175cv','1995','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'TOYOTA','MR2','MR2(10/1989 - 11/1989)','2.0 i coupé 156cv','1994','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'TOYOTA','CELICA','TA (1/1970 - 07/1977)','GT 1.6 LIFTBACK','1974','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'BMW','SERIE 1','Série 1 E81','130 i 3.0 265cv','2012','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'BMW','SERIE 2','Série 2 E81','M235 i 3.0 325cv','2014','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'BMW','SERIE 3','Série 3 E30','M235 i 3.0 325cv','2014','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'BMW','SERIE 5','Série 5 E30','','1985','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'BMW','SERIE 5','Série 5 E36','','1985','','12');
INSERT INTO vehicule (categorie, marque, famille,modele,type,year,vin,voltage) VALUES ('Voiture', 'BMW','SERIE 7','Série 7 E36','','1988','','12');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de plaisance de Lorient');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de plaisance de Kernevel');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de plaisance de Guidel');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de plaisance de Carnac');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de plaisance de Locmiquélic');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de plaisance de Gavre');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de Vannes');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de Saint-Goustan');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de Guilvin');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de Lagaden');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port d\Arradon');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Embarcadère Ile d\arz');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de Locmariaquer');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port du Magouër');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port d\Étel');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port Niscop');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de Saint Cado');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de Riantec');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de la Trinité-sur-mer');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de Belz');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port Haliguen Quiberon');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de Quiberon');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de Pen Mané');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de port-Louis');
INSERT INTO poi (categorie, nomPOI) VALUES ('Port', 'Port de la base de Lorient');
INSERT INTO poi (categorie, nomPOI) VALUES ('Aéroport', 'Aéroport de Lorient Bretagne Sud');
INSERT INTO poi (categorie, nomPOI) VALUES ('Aéroport', 'Aéroport de Vannes-Golfe du Morbihan');
INSERT INTO poi (categorie, nomPOI) VALUES ('Gare', 'Gare de Lorient SNCF');
INSERT INTO poi (categorie, nomPOI) VALUES ('Gare', 'Gare de Vannes SNCF');