INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de plaisance de Lorient');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de plaisance de Kernevel');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de plaisance de Guidel');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de plaisance de Carnac');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de plaisance de Locmiquélic');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de plaisance de Gavre');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de Vannes');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de Saint-Goustan');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de Guilvin');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de Lagaden');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port d\Arradon');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Embarcadère Ile d\arz');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de Locmariaquer');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port du Magouër');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port d\Étel');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port Niscop');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de Saint Cado');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de Riantec');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de la Trinité-sur-mer');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de Belz');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port Haliguen Quiberon');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de Quiberon');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de Pen Mané');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de port-Louis');
INSERT INTO poi (categorie, nom) VALUES ('Port', 'Port de la base de Lorient');
INSERT INTO poi (categorie, nom) VALUES ('Aéroport', 'Aéroport de Lorient Bretagne Sud');
INSERT INTO poi (categorie, nom) VALUES ('Aéroport', 'Aéroport de Vannes-Golfe du Morbihan');
INSERT INTO poi (categorie, nom) VALUES ('Gare', 'Gare de Lorient SNCF');
INSERT INTO poi (categorie, nom) VALUES ('Gare', 'Gare de Vannes SNCF');